model:
  type: "ids_gru" # İsim loglarda görünsün
  num_classes: 8
  input_dim: 39

data:
  batch_size: 256 # GRU 256 ile daha mutlu olur (Gradientler ortalanır)
  num_workers: 0

training:
  epochs: 50
  
  learning_rate: 0.0003  # DÜŞÜRDÜK: 0.001 çok agresif geldi, zikzak yaptı.
  weight_decay: 0.0001
  
  optimizer: "adamw"

  scheduler: "plateau"
  scheduler_patience: 3
  scheduler_factor: 0.5
  
  early_stopping_patience: 10

checkpoint:
  save_dir: "models/checkpoints/ids_multiclass_gru_final"

logging:
  verbose: true

seed: 42