# ============================================================
# NANO-PRIME CONFIG (Lightweight & Aggressive)
# ============================================================

model:
  type: "ids_resnet_nano_prime" # İsim sadece log için
  num_classes: 7
  input_dim: 39

data:
  # Model çok hafif olduğu için 512 veya 1024 yapabilirsin.
  # Hız için 512 idealdir.
  batch_size: 512
  num_workers: 4

training:
  epochs: 60
  
  # Model küçük olduğu için biraz daha agresif bir LR ile başlıyoruz.
  learning_rate: 0.002 
  
  weight_decay: 0.0001
  
  optimizer: "adamw"

  # Cosine Annealing: LR'yi dalgalandırarak yerel minimumlardan kaçar.
  scheduler: "cosine" 
  
  early_stopping_patience: 15

checkpoint:
  # Kayıt yeri
  save_dir: "models/checkpoints/ids_nano_prime_hybrid_focal_groupNorm_gan"

logging:
  verbose: true

seed: 42