model:
  type: "ids_resnet_mlp"
  num_classes: 8
  input_dim: 39

data:
  batch_size: 256
  num_workers: 0

training:
  epochs: 70            # Attention olduğu için öğrenme biraz daha uzun sürebilir
  
  learning_rate: 0.001  # Sabit
  weight_decay: 0.0001  # İdeal
  
  optimizer: "adamw"

  scheduler: "plateau"
  scheduler_patience: 5      # 5 Epoch bekle
  scheduler_factor: 0.5      # Yarıya düşür (Sert düşürme, yumuşak in)
  
  early_stopping_patience: 15

checkpoint:
  save_dir: "models/checkpoints/ids_multiclass_se_attention"

logging:
  verbose: true

seed: 42