model:
  type: "ids_resnet_nano"  # Nano'ya döndük
  num_classes: 7
  input_dim: 39

data:
  batch_size: 256
  num_workers: 0

training:
  epochs: 60
  learning_rate: 0.001 
  
  # Nano için standart weight decay
  weight_decay: 0.0001
  
  optimizer: "adamw"
  scheduler: "plateau"
  scheduler_patience: 7   
  scheduler_factor: 0.7   
  early_stopping_patience: 15

checkpoint:
  # Klasör ismi: Nano + Wide + Aggressive Loss
  save_dir: "models/checkpoints/ids_multiclass_nano_final_jointloss"

logging:
  verbose: true

seed: 42