model:
  type: "ids_resnet_nano_plus_pure" 
  num_classes: 8 
  input_dim: 39

data:
  batch_size: 256
  num_workers: 0

training:
  epochs: 60
  
  # Klasik yapı (ReLU) için en iyi hız.
  learning_rate: 0.001 
  
  weight_decay: 0.0001
  optimizer: "adamw"
  
  scheduler: "plateau"
  scheduler_patience: 2
  scheduler_factor: 0.5
  
  early_stopping_patience: 12

checkpoint:
  # Karışmasın diye ismini net koydum
  save_dir: "models/checkpoints/ids_nano_plus_pure_24ch"

logging:
  verbose: true

seed: 42